CREATE DATABASE IF NOT EXISTS FIND_DOCTOR;
USE FIND_DOCTOR;

CREATE TABLE IF NOT EXISTS USERS(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(50) NOT NULL,
    USER_TYPE VARCHAR(50) NOT NULL,
    PRIMARY KEY(USER_ID)
);